---
version: '3.7'

services:
  boxdb:
    build:
      context: .
    image: boxdb:0.0.3
    volumes:
      - type: bind
        source: .
        target: /home/boxdb
    ports:
      - "5000:5000"
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
  mongo:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - type: bind
        source: ./data
        target: /root/data
      - type: volume
        source: mongo-volume
        target: /data/db

volumes:
  mongo-volume:
...
