---
version: '3.7'

services:
  boxdb:
    build:
      context: .
    image: boxdb:0.0.4
    volumes:
      - type: bind
        source: .
        target: /home/boxdb/dev
    networks:
      - boxdb-internal-net
      - boxdb-external-net
    ports:
      - "5000:5000"
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
  mongo:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: boxdb
      MONGO_INITDB_ROOT_PASSWORD: boxdb
    volumes:
      - type: bind
        source: ./data
        target: /root/data
      - type: volume
        source: boxdb-volume
        target: /data/db
    networks:
      - boxdb-internal-net

volumes:
  boxdb-volume:

networks:
  boxdb-internal-net:
    internal: true
    name: boxdb-internal-net
  boxdb-external-net:
    name: boxdb-external-net
...
