# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gcommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gcommand.proto',
  package='gcommand',
  syntax='proto3',
  serialized_pb=_b('\n\x0egcommand.proto\x12\x08gcommand\";\n\x07\x43ommand\x12\x0f\n\x07\x62oxname\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x01(\t\"\x1e\n\tReturnMsg\x12\x11\n\treturnMsg\x18\x01 \x01(\t2H\n\rRemoteCommand\x12\x37\n\x0b\x45xecCommand\x12\x11.gcommand.Command\x1a\x13.gcommand.ReturnMsg\"\x00\x42*Z(github.com/ronaldoafonso/boxcmd/gcommandb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='gcommand.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boxname', full_name='gcommand.Command.boxname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='gcommand.Command.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='gcommand.Command.params', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=87,
)


_RETURNMSG = _descriptor.Descriptor(
  name='ReturnMsg',
  full_name='gcommand.ReturnMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='returnMsg', full_name='gcommand.ReturnMsg.returnMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['ReturnMsg'] = _RETURNMSG

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'gcommand_pb2'
  # @@protoc_insertion_point(class_scope:gcommand.Command)
  ))
_sym_db.RegisterMessage(Command)

ReturnMsg = _reflection.GeneratedProtocolMessageType('ReturnMsg', (_message.Message,), dict(
  DESCRIPTOR = _RETURNMSG,
  __module__ = 'gcommand_pb2'
  # @@protoc_insertion_point(class_scope:gcommand.ReturnMsg)
  ))
_sym_db.RegisterMessage(ReturnMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z(github.com/ronaldoafonso/boxcmd/gcommand'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class RemoteCommandStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ExecCommand = channel.unary_unary(
          '/gcommand.RemoteCommand/ExecCommand',
          request_serializer=Command.SerializeToString,
          response_deserializer=ReturnMsg.FromString,
          )


  class RemoteCommandServicer(object):

    def ExecCommand(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RemoteCommandServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ExecCommand': grpc.unary_unary_rpc_method_handler(
            servicer.ExecCommand,
            request_deserializer=Command.FromString,
            response_serializer=ReturnMsg.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'gcommand.RemoteCommand', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRemoteCommandServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ExecCommand(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRemoteCommandStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ExecCommand(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    ExecCommand.future = None


  def beta_create_RemoteCommand_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('gcommand.RemoteCommand', 'ExecCommand'): Command.FromString,
    }
    response_serializers = {
      ('gcommand.RemoteCommand', 'ExecCommand'): ReturnMsg.SerializeToString,
    }
    method_implementations = {
      ('gcommand.RemoteCommand', 'ExecCommand'): face_utilities.unary_unary_inline(servicer.ExecCommand),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_RemoteCommand_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('gcommand.RemoteCommand', 'ExecCommand'): Command.SerializeToString,
    }
    response_deserializers = {
      ('gcommand.RemoteCommand', 'ExecCommand'): ReturnMsg.FromString,
    }
    cardinalities = {
      'ExecCommand': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'gcommand.RemoteCommand', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
