# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import gcommand_pb2 as gcommand__pb2


class RemoteCommandStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecCommand = channel.unary_unary(
        '/gcommand.RemoteCommand/ExecCommand',
        request_serializer=gcommand__pb2.Command.SerializeToString,
        response_deserializer=gcommand__pb2.ReturnMsg.FromString,
        )


class RemoteCommandServicer(object):

  def ExecCommand(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteCommandServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecCommand': grpc.unary_unary_rpc_method_handler(
          servicer.ExecCommand,
          request_deserializer=gcommand__pb2.Command.FromString,
          response_serializer=gcommand__pb2.ReturnMsg.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gcommand.RemoteCommand', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
