---
apiVersion: v1
kind: Service
metadata:
  name: boxdb-api
  namespace: boxdb
spec:
  type: LoadBalancer
  selector:
    app: boxdb
    version: v1.0
  ports:
    - port: 8080
      targetPort: 5000
      protocol: TCP
