apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boxdb-pvc
  namespace: boxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi
  storageClassName: ""
