apiVersion: v1
kind: PersistentVolume
metadata:
  name: boxdb-pv
  namespace: boxdb
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.1
    path: "/srv/nfs4/boxdb"
