---
apiVersion: v1
kind: Service
metadata:
  name: boxdb
  namespace: boxdb
spec:
  type: NodePort
  selector:
    app: boxdb
    version: v1.0
  ports:
    - port: 5000
      nodePort: 30000
      targetPort: 5000
      protocol: TCP
