---
apiVersion: v1
kind: Service
metadata:
  name: boxdb-api
  namespace: boxdb
spec:
  type: NodePort
  selector:
    app: boxdb
    version: v1.0
  ports:
    - port: 30000
      nodePort: 30000
      protocol: TCP
