---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxdb-api
  namespace: boxdb
spec:
  selector:
    matchLabels:
      app: boxdb
      version: v1.0
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: boxdb
        version: v1.0
    spec:
      containers:
        - name: boxdb
          image: ronaldoafonso/boxdb:0.0.11
          ports:
            - containerPort: 30000
              name: boxdb
              protocol: TCP
          env:
            - name: BOXCMD
              valueFrom:
                secretKeyRef:
                  name: boxdb-secrets
                  key: boxcmd
            - name: BOXDB_MONGO
              valueFrom:
                secretKeyRef:
                  name: boxdb-secrets
                  key: boxdb_mongo
            - name: BOXDB_MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: boxdb-secrets
                  key: boxdb_mongo_username
            - name: BOXDB_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: boxdb-secrets
                  key: boxdb_mongo_password
          readinessProbe:
            tcpSocket:
              port: 30000
            initialDelaySeconds: 10
            periodSeconds: 60
